// Generated by CoffeeScript 2.7.0
var adjust_color_brightness, any_square, available_colors, color_to_string, get_n_cube_cells, group_n_cells, random_color, render_rotating_cube, sort_cells_by_edges,
  indexOf = [].indexOf;

random_color = function() {
  return [Math.floor(Math.random() * 256), Math.floor(Math.random() * 256), Math.floor(Math.random() * 256)];
};

color_to_string = function(a) {
  return `rgb(${a[0]}, ${a[1]}, ${a[2]})`;
};

available_colors = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11].map(function(a) {
  return random_color();
});

adjust_color_brightness = function(a, factor) {
  return a.map(function(a) {
    return Math.min(255, Math.max(0, a * factor));
  });
};

any_square = function(cells, f) {
  // array {array -> any} -> any
  // apply Array.find only on 2-cells and return the first truthy result
  if (4 === cells.length && 2 === cells[0].length && Number.isInteger(cells[0][0])) {
    return f(cells);
  } else {
    return any(cells, function(a) {
      return any_square(a, f);
    });
  }
};

sort_cells_by_edges = function(cells, n, k, cell_length) {
  var i, includes_edge, is_adjacent, is_adjacent_parallel, j, link, max_shared_edges, ref;
  // array integer integer integer -> array
  if (2 === cell_length) {
    // sort edge vertices to form a continuous line
    is_adjacent = function(a, b) {
      return a.some(function(a) {
        return indexOf.call(b, a) >= 0;
      });
    };
    cells = sort_by_predicate(cells, is_adjacent);
    link = cells[0].find(function(a) {
      return indexOf.call(cells[1], a) >= 0;
    });
    if (link !== cells[0][1]) {
      array_swap(cells[0], 0, 1);
    }
    for (i = j = 1, ref = cells.length; (1 <= ref ? j < ref : j > ref); i = 1 <= ref ? ++j : --j) {
      if (cells[i - 1][1] !== cells[i][0]) {
        array_swap(cells[i], 1, 0);
      }
    }
    return cells;
  } else {
    // sort other cells by adjacency and parallelity
    max_shared_edges = 2 ** (n - k - 2);
    includes_edge = function(a, b) {
      return a.find(function(a) {
        return edge_equal(a, b);
      });
    };
    is_adjacent_parallel = function(a, b) {
      return any_square(a, function(a) {
        return any_square(b, function(b) {
          var shared;
          shared = intersection(a, b, max_shared_edges, includes_edge);
          if (shared) {
            // checks that only the x-axis differs. could be extended
            if (1 === (shared[0][0] ^ shared[0][1])) {
              return 2;
            } else {
              return 1;
            }
          } else {
            return 0;
          }
        });
      });
    };
    return sort_by_predicate(cells, is_adjacent_parallel);
  }
};

group_n_cells = function(vertices, n, k, cell_length) {
  var a, cell_vertices, cells, fixed, fixed_combinations, j, key, l, len, len1, new_cells;
  fixed_combinations = get_bit_combinations(n, k);
  cells = [];
  for (j = 0, len = fixed_combinations.length; j < len; j++) {
    fixed = fixed_combinations[j];
    cell_vertices = {};
    for (l = 0, len1 = vertices.length; l < len1; l++) {
      a = vertices[l];
      key = fixed & a;
      if (cell_vertices[key]) {
        cell_vertices[key].push(a);
      } else {
        cell_vertices[key] = [a];
      }
    }
    new_cells = Object.values(cell_vertices).filter(function(a) {
      return cell_length === a.length;
    });
    cells = cells.concat(new_cells);
  }
  return cells;
};

get_n_cube_cells = function(n) {
  var ref, subcells;
  // integer -> array
  // get edges grouped by nested cells
  subcells = function(cells, k) {
    var a, cell_length;
    if (k < n) {
      cell_length = 2 ** (n - k);
      cells = group_n_cells(cells, n, k, cell_length);
      cells = (function() {
        var j, len, results;
        results = [];
        for (j = 0, len = cells.length; j < len; j++) {
          a = cells[j];
          results.push(subcells(a, k + 1));
        }
        return results;
      })();
      return sort_cells_by_edges(cells, n, k, cell_length);
    } else {
      return cells;
    }
  };
  return subcells((function() {
    var results = [];
    for (var j = 0, ref = 2 ** n; 0 <= ref ? j < ref : j > ref; 0 <= ref ? j++ : j--){ results.push(j); }
    return results;
  }).apply(this), 1);
};

render_rotating_cube = function(options) {
  var angle, cells, draw, f, gl, interval, render_square_path, render_vertex, rotate, rotate_f, space;
  // object -> interval
  // repeatedly draw and rotate a cube.
  rotate_f = function(space) {
    var rotators;
    // one rotation function per plane
    rotators = Array(options.dimensions).fill(0).map(function(a, index) {
      var data, ia, ib;
      if (0 === options.rotate_dimensions[index]) {
        return function(a, angle) {
          return a;
        };
      }
      data = Array(options.dimensions).fill(0);
      ia = (index + 1) % options.dimensions;
      ib = index;
      return function(a, angle) {
        var rotor;
        angle = angle + ((ia + 1) * 1000);
        // array number -> array
        data[ia] = Math.cos(angle);
        data[ib] = Math.sin(angle);
        // create a versorjs object
        rotor = space.Vec.apply(this, data);
        return space.Vec.apply(this, a).sp(rotor).toArray();
      };
    });
    return function(a, angle) {
      var f;
      // apply all rotation functions to the given point vector
      f = function(a, rotate) {
        return a && rotate(a, angle);
      };
      return rotators.reduce(f, a);
    };
  };
  render_square_path = function(a) {
    var b, distance, midpoint, midpoint_distance;
    midpoint = line_midpoint(a[0][0], a[2][0]);
    midpoint_distance = vertex_distance(midpoint);
    [b, distance] = render_vertex(a[0][0]);
    return [b, midpoint_distance];
  };
  draw = function(ctx, cells, render_vertex, angle) {
    var draw_cells;
    ctx.clearRect(0, 0, options.canvas_width, options.canvas_height);
    draw_cells = function(a, ai) {
      var color, color_string, distance, i, j, midpoint, point, ref;
      if (4 === a.length && 2 === a[0].length) {
        [point, distance] = render_vertex(a[0][0]);
        midpoint = ctx.beginPath();
        ctx.moveTo(point[0], point[1]);
        point = render_vertex(a[0][1]);
        ctx.lineTo(point[0], point[1]);
        for (i = j = 1, ref = a.length; (1 <= ref ? j < ref : j > ref); i = 1 <= ref ? ++j : --j) {
          point = render_vertex(a[i][1]);
          ctx.lineTo(point[0], point[1]);
        }
        ctx.closePath();
        //distance = vertex_distance
        color = available_colors[ai];
        color_string = color_to_string(adjust_color_brightness(color, 1));
        ctx.strokeStyle = color_string;
        ctx.fillStyle = color_string;
        ctx.stroke();
        //ctx.fill()
        return gl.drawElements(gl.LINES, vertex_count, type, offset);
      } else {
        return a.forEach(function(a, ai) {
          return draw_cells(a, ai);
        });
      }
    };
    draw_cells(cells, 0);
    return angle + options.rotation_speed;
  };
  gl = options.canvas.getContext("webgl");
  if (!gl) {
    alert("unable to initialize webgl. your browser may not support it.");
    return;
  }
  console.log(gl);
  return;
  angle = 0;
  space = versor.create({
    metric: Array(options.dimensions).fill(1)
  });
  rotate = rotate_f(space);
  render_vertex = function(a) {
    var d;
    a = rotate(a, angle);
    d = vertex_distance(a);
    a = perspective_project(canvas_width, canvas_height, a, d);
    return [a, d];
  };
  cells = get_n_cube_cells(options.dimensions);
  cells = array_map_leafs(cells, (function(a) {
    return bits_to_array(a, options.dimensions);
  }));
  // called repeatedly and updates angle
  f = function() {
    return angle = draw(ctx, cells, render_vertex, angle);
  };
  interval = setInterval(f, options.refresh);
  return interval;
};
