#!/bin/sh

export SC_LOAD_PATH=$PWD
warnings="-Wunused-label -Wunused-value -Wunused-variable"
gcc_options="$warnings -Wfatal-errors -std=c11 -O2 -g"

compile_export_2015() {
  sc source/sc/export-2015.sc temp/export-2015.c
  gcc $gcc_options -llmdb temp/export-2015.c -o exe/dg-export-2015 && chmod -R 755 temp &&
  rm temp/export-2015.c
}

compile_add_intern_type_2017() {
  n=add-intern-type-2017
  sc source/sc/$n.sc temp/$n.c &&
  gcc $gcc_options -llmdb -lsph-dg temp/$n.c -o exe/dg-$n && chmod -R 755 temp &&
  rm temp/$n.c
}

mkdir -p temp &&
compile_add_intern_type_2017 $@
#compile_export_2015 $@
