(require (quote color-theme))

(defun color-theme-sph-dark ()
  (interactive)
  (color-theme-install
    '(color-theme-sph-dark
      ((foreground-color . "#b2b2b2")
        (background-mode . dark))
      (bold ((t (:bold t))))
      (bold-italic ((t (:italic t :bold t))))
      (default ((t (nil))))
      (font-lock-keyword-face ((t (:foreground "#f5f5f5"))))
      (font-lock-function-name-face ((t (:foreground "#A8E4A0"))))
      (font-lock-type-face ((t (:foreground "eeeeee"))))
      (font-lock-builtin-face ((t (:bold t :foreground "#6082B6"))))
      (font-lock-preprocessor-face ((t (:foreground "#d7d787"))))
      (font-lock-constant-face ((t (:foreground "#8DACDB"))))
      (font-lock-variable-name-face ((t (:foreground "#ffffff"))))
      (font-lock-string-face ((t (:foreground "#3a3a3a"))))
      (font-lock-comment-face ((t (:foreground "#444444"))))
      (font-lock-doc-face ((t (:foreground "#666666"))))
      (sph-scheme-parentheses-face ((t (:foreground "#666666"))))
      (show-paren-match-face ((t (:foreground "#eeeeee" :background "#333333"))))
      (region ((t (:foreground "#eeeeee" :background nil))))
      (isearch ((t (:foreground "#eeeeee" :background nil))))
      (lazy-highlight ((t (:foreground "#eeeeee" :background "#222222"))))
      (mode-line ((t (nil))))
      (minibuffer-prompt ((t (nil)))))))

(defun color-theme-sph-dark-minimal ()
  (interactive)
  (color-theme-install
    '(color-theme-sph-dark-minimal
      ((background-mode . dark))
      (font-lock-comment-face ((t (:foreground "#444444"))))
      (font-lock-comment-delimiter-face ((t (:foreground "#666666"))))
      (font-lock-function-name-face ((t (nil))))
      (show-paren-match-face ((t (:foreground "#ffffff"))))
      (font-lock-variable-name-face ((t (:foreground "#888888"))))
      (font-lock-keyword-face ((t (:foreground "#888888"))))
      (default ((t (nil))))
      (font-lock-type-face ((t (nil))))
      (font-lock-builtin-face ((t (nil))))
      (font-lock-preprocessor-face ((t (nil))))
      (font-lock-constant-face ((t (nil))))
      (font-lock-doc-face ((t (:foreground "#888888"))))
      (font-lock-string-face ((t (:foreground "#666666"))))
      (region ((t (nil))))
      (isearch ((t (:foreground "#eeeeee" :background nil))))
      (lazy-highlight ((t (:foreground "#eeeeee" :background "#222222"))))
      (mode-line ((t (nil))))
      (minibuffer-prompt ((t (nil)))))))

(defun color-theme-sph-light ()
  (interactive)
  (color-theme-install
    '(color-theme-sph-light
      ((foreground-color . "#000000")
        (background-color . "grey00")
        (background-mode . light))
      (bold ((t (:bold t))))
      (bold-italic ((t (:italic t :bold t))))
      (default ((t (nil))))
      (font-lock-keyword-face ((t (:foreground "#101010" :bold t))))
      (font-lock-function-name-face ((t (:bold t :foreground "#571B5F"))))
      (font-lock-builtin-face ((t (:bold t :foreground "#9F7D49"))))
      (font-lock-string-face ((t (:foreground "#666666" :background "#eaeaea"))))
      (font-lock-preprocessor-face ((t (:foreground "#001484"))))
      (font-lock-constant-face ((t (:foreground "#725324"))))
      (font-lock-type-face ((t (:foreground "#819A43"))))
      (font-lock-variable-name-face ((t (:bold t :foreground "#444444"))))
      (font-lock-comment-face ((t (:foreground "#868686"))))
      (show-paren-match-face ((t (:foreground "#000000" :background "#69778d"))))
      (region ((t (:foreground nil :background "#615c53"))))
      (mode-line ((t (:foreground "#5c5c5c" :background "#dddddd")))))))
