#!/usr/bin/guile
!#

(import (sph common) (sph cli) (sph fun shitty-variable-name-generator))

(define (svn-cli)
  (let (arguments ((cli-create (list-q (result-count word-part ...) #f #t))))
    (and-let*
      ( (words (false-if-exception (string-join (alist-ref-q arguments word-part) " ")))
        (result-count
          (false-if-exception (string->number (alist-ref-q arguments result-count)))))
      (each display-line (svn-multiple result-count words)))))

(svn-cli)
